//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLOBSqlToJpeg
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBPictureDBEntities : DbContext
    {
        public DBPictureDBEntities()
            : base("name=DBPictureDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FILTEREDPICTURES> FILTEREDPICTURES { get; set; }
        public virtual DbSet<HALFBAD> HALFBAD { get; set; }
        public virtual DbSet<PERSONNEL> PERSONNEL { get; set; }
        public virtual DbSet<MMOBJS> MMOBJS { get; set; }
    }
}
