//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLOBSqlToJpeg
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONEL
    {
        public short EMPID { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string LNL_BLOB { get; set; }
        public Nullable<byte> OBJECT { get; set; }
        public Nullable<byte> TYPE { get; set; }
    }
}
