//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLOBSqlToJpeg
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONEL
    {
        public short EMPID { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string LNL_BLOB { get; set; }
        public Nullable<byte> OBJECT { get; set; }
        public Nullable<byte> TYPE { get; set; }
    }
}
