'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Adresse
    Public Property id As Integer
    Public Property id_adres As String
    Public Property id_entit As String
    Public Property id_type As String
    Public Property no_voie As String
    Public Property id_typvo As String
    Public Property lb_voie As String
    Public Property adr2 As String
    Public Property codposta As String
    Public Property ville As String
    Public Property bureau As String
    Public Property id_pays As String
    Public Property etat As String
    Public Property dt_fin As Nullable(Of Date)
    Public Property id_ayant As String
    Public Property no_benef As String
    Public Property IntegreDansBachON As Nullable(Of Boolean)

End Class
