'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Assemblee
    Public Property IdAssemblee As Integer
    Public Property Exercice As String
    Public Property DateDuJour As String
    Public Property Horaire As String
    Public Property Lieu As String
    Public Property Adresse As String
    Public Property OrdreDuJourFichier As String
    Public Property LeJourEnTexte As String
    Public Property Actuelle As Nullable(Of Boolean)

    Public Overridable Property DocumentDisponible As ICollection(Of DocumentDisponible) = New HashSet(Of DocumentDisponible)

End Class
