'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AyantDro
    Public Property id_ayant As String
    Public Property no_adher As String
    Public Property no_nonAd As String
    Public Property id_civil As String
    Public Property nom As String
    Public Property prenom As String
    Public Property prenom2 As String
    Public Property nomJF As String
    Public Property pseudo1 As String
    Public Property pseudo2 As String
    Public Property pseudo3 As String
    Public Property dt_naiss As Nullable(Of Date)
    Public Property lieuNaiss As String
    Public Property id_pays As String
    Public Property id_secu As String
    Public Property no_conge As String
    Public Property lb_profe As String
    Public Property id1Instr As String
    Public Property id2Instr As String
    Public Property id3Instr As String
    Public Property groupe As String
    Public Property lstOrgan As String
    Public Property dt_adhes As Nullable(Of Date)
    Public Property mt_ParSo As Nullable(Of Decimal)
    Public Property dt_sorti As Nullable(Of Date)
    Public Property lb_sorti As String
    Public Property typSorti As String
    Public Property co_deces As String
    Public Property dt_deces As Nullable(Of Date)
    Public Property dtDAppDG As Nullable(Of Date)
    Public Property dtFAppDG As Nullable(Of Date)
    Public Property no_dossi As String
    Public Property id_doubl As String
    Public Property no_ipd As String
    Public Property dt_creat As Nullable(Of Date)
    Public Property dt_maj As Nullable(Of Date)
    Public Property id_etat As String
    Public Property notes As String
    Public Property idCUtili As String
    Public Property idMUtili As String
    Public Property no_sai As String
    Public Property no_adami As String
    Public Property noCAdami As String
    Public Property noCSpedi As String
    Public Property NaAd As String
    Public Property password As String
    Public Property dt_pwEnvoi As Nullable(Of Date)
    Public Property ipd_PC As String
    Public Property ipd_BR As String
    Public Property ipd_CP As String
    Public Property ipd_MA As String
    Public Property ipd_LE As String
    Public Property ipd_PP As String
    Public Property ipd_RE As String
    Public Property ipd_RP As String
    Public Property ipd_RR As String
    Public Property ipd_dup As Nullable(Of Boolean)
    Public Property ipd_verif As Nullable(Of Boolean)
    Public Property ipd_dtVer As Nullable(Of Date)
    Public Property IntegreDansBachON As Nullable(Of Boolean)

    Public Overridable Property Benefici As ICollection(Of Benefici) = New HashSet(Of Benefici)
    Public Overridable Property TacheHistorisees As ICollection(Of TacheHistorisee) = New HashSet(Of TacheHistorisee)

End Class
