'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Benefici
    Public Property id_benef As String
    Public Property id_ayant As String
    Public Property no_benef As String
    Public Property QuaBenef As String
    Public Property id_civil As String
    Public Property nom As String
    Public Property prenom As String
    Public Property prenom2 As String
    Public Property nomjf As String
    Public Property no_telfi As String
    Public Property no_telpo As String
    Public Property no_telec As String
    Public Property mele As String
    Public Property dt_naiss As Nullable(Of Date)
    Public Property lieunaiss As String
    Public Property id_pays As String
    Public Property dt_sorti As Nullable(Of Date)
    Public Property lb_sorti As String
    Public Property typsorti As String
    Public Property co_deces As String
    Public Property dt_deces As Nullable(Of Date)
    Public Property tx_quoti As Nullable(Of Decimal)
    Public Property txrdroit As Nullable(Of Decimal)
    Public Property txrvmp As Nullable(Of Decimal)
    Public Property txrdat As Nullable(Of Decimal)
    Public Property id_modpa As String
    Public Property nombanqu As String
    Public Property co_banqu As String
    Public Property co_guich As String
    Public Property co_compt As String
    Public Property clerib As String
    Public Property bic As String
    Public Property aba As String
    Public Property iban As String
    Public Property lb_domic As String
    Public Property ad1banqu As String
    Public Property ad2banqu As String
    Public Property cp_banqu As String
    Public Property vilbanq As String
    Public Property paybanqu As String
    Public Property id2benef As String
    Public Property notes As String
    Public Property id_etat As String
    Public Property ribvalab As Nullable(Of Boolean)
    Public Property instit_can As String
    Public Property branch_can As String
    Public Property IntegreDansBachON As Nullable(Of Boolean)

    Public Overridable Property AyantDro As AyantDro

End Class
