'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DeclarationFiscale
    Public Property IdDeclarationFiscale As Integer
    Public Property Annee As String
    Public Property NomDuFichier As String
    Public Property NumeroIdAyant As String

End Class
