'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DeclarationFiscaleFinale
    Public Property IdDeclarationFiscale As Integer
    Public Property Annee As String
    Public Property NomDuFichier As String
    Public Property MontantNet As Single
    Public Property DroitsBruts As String
    Public Property PrelevementSocial As String
    Public Property CSGDeductible As String
    Public Property NetImposable As String
    Public Property NumeroIdAyant As String
    Public Property IdSpedinaute As Integer

End Class
