'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DetailsDeRepartion
    Public Property IdDetailsDeRepartion As Integer
    Public Property FichierDetail As String
    Public Property IdRepartition As Integer
    Public Property IdSpedinaute As Integer

    Public Overridable Property Repartition As RepartitionGenerale
    Public Overridable Property Spedinaute As Spedinaute
    Public Overridable Property Feuille As ICollection(Of Feuille) = New HashSet(Of Feuille)

End Class
