'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DocumentDisponible
    Public Property IdDocumentDisponible As Integer
    Public Property IdAssemblee As Integer
    Public Property NumeroDOrdre As String
    Public Property TitreDuSujet As String
    Public Property EmplacementDuFichier As String

    Public Overridable Property Assemblee As Assemblee

End Class
