'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class FacilDBEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=FacilDBEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Instruments() As DbSet(Of Instrument)
    Public Overridable Property MotDePasses() As DbSet(Of MotDePasse)
    Public Overridable Property Pays() As DbSet(Of Pays)
    Public Overridable Property RepartitionGenerales() As DbSet(Of RepartitionGenerale)
    Public Overridable Property RibIbans() As DbSet(Of RibIban)
    Public Overridable Property SpedAdresses() As DbSet(Of SpedAdresse)
    Public Overridable Property Spedinautes() As DbSet(Of Spedinaute)
    Public Overridable Property TacheEffectuees() As DbSet(Of TacheEffectuee)
    Public Overridable Property TypeAdresses() As DbSet(Of TypeAdresses)
    Public Overridable Property TypeDeVoies() As DbSet(Of TypeDeVoies)
    Public Overridable Property DeclarationFiscales() As DbSet(Of DeclarationFiscale)
    Public Overridable Property DetailsDeRepartions() As DbSet(Of DetailsDeRepartion)
    Public Overridable Property Assemblees() As DbSet(Of Assemblee)
    Public Overridable Property DocumentDisponibles() As DbSet(Of DocumentDisponible)
    Public Overridable Property Feuilles() As DbSet(Of Feuille)
    Public Overridable Property Informations() As DbSet(Of Information)
    Public Overridable Property Mandataires() As DbSet(Of Mandataire)
    Public Overridable Property Mandats() As DbSet(Of Mandat)
    Public Overridable Property TypeDeMandats() As DbSet(Of TypeDeMandat)
    Public Overridable Property DeclarationFiscaleFinales() As DbSet(Of DeclarationFiscaleFinale)

End Class
