'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Feuille
    Public Property IdFeuille As Integer
    Public Property NumeroDeFeuille As String
    Public Property IntituleGeneral As String
    Public Property IdDetailsDeRepartion As Integer

    Public Overridable Property DetailsDeRepartion As DetailsDeRepartion
    Public Overridable Property Information As ICollection(Of Information) = New HashSet(Of Information)

End Class
