'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Information
    Public Property IdInformation As Integer
    Public Property DateEnregistrement As String
    Public Property TitreOeuvre As String
    Public Property ArtistePrincipalOuGroupe As String
    Public Property Compositeur As String
    Public Property Destinations As String
    Public Property IdFeuille As Integer
    Public Property NumeroDeFeuille As String

    Public Overridable Property Feuille As Feuille

End Class
