'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Instrument
    Public Property id_instr As Integer
    Public Property raninstr As Nullable(Of Integer)
    Public Property lb_instr As String
    Public Property no_instr As String
    Public Property scapr As String
    Public Property lb_scapr As String
    Public Property typscapr As String

    Public Overridable Property Spedinaute As ICollection(Of Spedinaute) = New HashSet(Of Spedinaute)

End Class
