'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Mandataire
    Public Property IdMandataire As Integer
    Public Property Prenom As String
    Public Property Nom As String
    Public Property AdresseEmail As String
    Public Property PasseMot As String
    Public Property Enligne As String
    Public Property DernierDateDeConnexion As Nullable(Of Date)
    Public Property MotDePasseOublie As Nullable(Of Boolean)
    Public Property IntegreDansBachON As Boolean

    Public Overridable Property Mandat As ICollection(Of Mandat) = New HashSet(Of Mandat)

End Class
