'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Mandat
    Public Property IdMandat As Integer
    Public Property IdTypeDeMandat As Integer
    Public Property DateDeDebut As String
    Public Property DateDeFin As String
    Public Property IdMandataire As Integer
    Public Property IdSpedinaute As Nullable(Of Integer)

    Public Overridable Property Mandataire As Mandataire
    Public Overridable Property Spedinaute As Spedinaute
    Public Overridable Property TypeDeMandat As TypeDeMandat

End Class
