'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MotDePasse
    Public Property IdMotDePasse As Integer
    Public Property DateDeCreation As Date
    Public Property DateDeRenvoi As Date
    Public Property Actuel As Boolean
    Public Property PasseMot As String
    Public Property IntegreDansBachON As Boolean
    Public Property IdSpedinaute As Integer

    Public Overridable Property Spedinautes As Spedinaute

End Class
