'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class OurDBEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=OurDBEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Adresses() As DbSet(Of Adresse)
    Public Overridable Property AyantDro() As DbSet(Of AyantDro)
    Public Overridable Property Benefici() As DbSet(Of Benefici)
    Public Overridable Property RibIbanArchives() As DbSet(Of RibIbanArchive)
    Public Overridable Property TacheHistorisees() As DbSet(Of TacheHistorisee)

End Class
