'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Pays
    Public Property id_pays As String
    Public Property id_Web As Nullable(Of Integer)
    Public Property lb_pays As String
    Public Property co_ipd As String
    Public Property on_ue As Boolean
    Public Property dt_ue As Nullable(Of Date)
    Public Property co_insee As String
    Public Property cfpcps As Nullable(Of Double)
    Public Property cfpcpa As Nullable(Of Double)
    Public Property cfpre As Nullable(Of Double)
    Public Property dt_rome As Nullable(Of Date)
    Public Property on_rome As Boolean
    Public Property est_sepa As Boolean
    Public Property long_iban As Nullable(Of Integer)
    Public Property pays_iban As String

    Public Overridable Property RibIbans As ICollection(Of RibIban) = New HashSet(Of RibIban)

End Class
