'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RepartitionGenerale
    Public Property IdRepartition As Integer
    Public Property Annee As String
    Public Property MoisRepartition As String
    Public Property TableDecodification As String
    Public Property ReglesDeRepartition As String
    Public Property LettreDAccompagnement As String

    Public Overridable Property DetailsDeRepartion As ICollection(Of DetailsDeRepartion) = New HashSet(Of DetailsDeRepartion)

End Class
