'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RibIbanArchive
    Public Property IdRibIban As Integer
    Public Property Titulaire As String
    Public Property BicSwift As String
    Public Property NumeroIBAN As String
    Public Property Domiciliation As String
    Public Property CodeBanque As String
    Public Property Guichet As String
    Public Property NumeroCompte As String
    Public Property CleRIB As String
    Public Property Pays As String
    Public Property DateDeSaisie As Nullable(Of Date)
    Public Property Actuel As Boolean
    Public Property IntegreDansBachON As Boolean
    Public Property IdSpedinaute As Integer
    Public Property id_ayant As String

End Class
