'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SpedAdresse
    Public Property IdAdresse As Integer
    Public Property TypeAdresse As String
    Public Property Numero As String
    Public Property TypeDeVoie As String
    Public Property LibelleVoie As String
    Public Property Adresse2 As String
    Public Property CodePostal As String
    Public Property Ville As String
    Public Property Bureau As String
    Public Property DateSaisie As Nullable(Of Date)
    Public Property Actuelle As Nullable(Of Boolean)
    Public Property IntegreDansBachON As Nullable(Of Boolean)
    Public Property IdSpedinaute As Integer
    Public Property Id_pays As String

    Public Overridable Property Spedinaute As Spedinaute
    Public Overridable Property TypeAdresses As TypeAdresses

End Class
