'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Spedinaute
    Public Property IdSpedinaute As Integer
    Public Property TypeDeProfil As String
    Public Property Civilite As String
    Public Property Prenom As String
    Public Property AutrePrenom As String
    Public Property Nom As String
    Public Property NomDeJeuneFille As String
    Public Property DateDeNaissance As Nullable(Of Date)
    Public Property LieuDeNaissance As String
    Public Property Nationalite As String
    Public Property NumeroDeMobile As String
    Public Property NumeroDeFixe As String
    Public Property AdresseEmail As String
    Public Property PasseMot As String
    Public Property NumeroIdAyant As String
    Public Property IPN As String
    Public Property NumeroAD As String
    Public Property NumeroNA As String
    Public Property ArtistePrincipalSpedidam As Nullable(Of Boolean) = false
    Public Property AccepterEmailInfos As String
    Public Property Enligne As String
    Public Property DernierDateDeConnexion As Nullable(Of Date)
    Public Property MotDePasseOublie As Nullable(Of Boolean)
    Public Property CompteUsurpe As Nullable(Of Boolean)
    Public Property DateDUsurpation As Nullable(Of Date)
    Public Property Pseudonyme1 As String
    Public Property Pseudonyme2 As String
    Public Property Pseudonyme3 As String
    Public Property Instrument1 As Nullable(Of Integer)
    Public Property Instrument2 As Nullable(Of Integer)
    Public Property Instrument3 As Nullable(Of Integer)
    Public Property Photo As String
    Public Property IntegreDansBachON As Nullable(Of Boolean) = false

    Public Overridable Property MotDePasses As ICollection(Of MotDePasse) = New HashSet(Of MotDePasse)
    Public Overridable Property TacheEffectuees As ICollection(Of TacheEffectuee) = New HashSet(Of TacheEffectuee)
    Public Overridable Property RibIban As ICollection(Of RibIban) = New HashSet(Of RibIban)
    Public Overridable Property SpedAdresse As ICollection(Of SpedAdresse) = New HashSet(Of SpedAdresse)
    Public Overridable Property DetailsDeRepartion As ICollection(Of DetailsDeRepartion) = New HashSet(Of DetailsDeRepartion)
    Public Overridable Property Mandat As ICollection(Of Mandat) = New HashSet(Of Mandat)
    Public Overridable Property Instrument As ICollection(Of Instrument) = New HashSet(Of Instrument)

End Class
