'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TacheHistorisee
    Public Property IdTacheHistorisee As Integer
    Public Property TypeDeTache As String
    Public Property DateDuJour As Date
    Public Property HeureCourante As System.TimeSpan
    Public Property IdAdresseConcernee As String
    Public Property IdModePasseConcerne As String
    Public Property IdRibIbanConcerne As String
    Public Property FicheConcernee As String
    Public Property Commentaire As String
    Public Property HistoriserON As Boolean
    Public Property IdSpedinaute As Integer
    Public Property Id_ayant As String

    Public Overridable Property AyantDro As AyantDro

End Class
