'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TacheEffectuee
    Public Property IdTacheEffectuee As Integer
    Public Property TypeDeTache As String
    Public Property DateDuJour As String
    Public Property HeureCourante As String
    Public Property IdAdresseConcernee As String
    Public Property IdModePasseConcerne As String
    Public Property IdRibIbanConcerne As String
    Public Property FicheConcernee As String
    Public Property NomDuDevice As String
    Public Property AdresseMac As String
    Public Property AdresseIP As String
    Public Property Commentaire As String
    Public Property HistoriserON As Boolean = false
    Public Property IdSpedinaute As Integer
    Public Property IntegreDansBachON As Boolean = false

    Public Overridable Property Spedinautes As Spedinaute

End Class
