//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbassyDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Decoupages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Decoupages()
        {
            this.Entites = new HashSet<Entites>();
        }
    
        public int Id { get; set; }
        public string Label { get; set; }
        public int IdPays { get; set; }
        public int IdTypeDecoupage { get; set; }
    
        public virtual Pays Pays { get; set; }
        public virtual TypeDecoupage TypeDecoupage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entites> Entites { get; set; }
    }
}
