//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbassyDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demandes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Demandes()
        {
            this.Documents = new HashSet<Documents>();
            this.Membres = new HashSet<Membres>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdEntite { get; set; }
        public string IdInstance { get; set; }
        public int Reference { get; set; }
        public System.DateTime DateCreation { get; set; }
        public int IdUtilisateur { get; set; }
        public bool EstGroupe { get; set; }
        public Nullable<int> IdTranche { get; set; }
        public string Ref { get; set; }
        public Nullable<int> IdNatureRequete { get; set; }
        public Nullable<int> IdTheme { get; set; }
        public string Objet { get; set; }
        public string TexteRequet { get; set; }
        public string ReponseRequete { get; set; }
        public Nullable<System.DateTime> DateRDVAuPlusTard { get; set; }
    
        public virtual NatureRequete NatureRequete { get; set; }
        public virtual Theme Theme { get; set; }
        public virtual Tranches Tranches { get; set; }
        public virtual Utilisateurs Utilisateurs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documents> Documents { get; set; }
        public virtual Immatriculation Immatriculation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Membres> Membres { get; set; }
    }
}
