//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbassyDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents
    {
        public int Id { get; set; }
        public string Label { get; set; }
        public string Path { get; set; }
        public Nullable<int> IdDocumentRequis { get; set; }
        public Nullable<int> IdDemande { get; set; }
        public int IdDocumentType { get; set; }
        public string MembreHelper { get; set; }
        public bool EstValide { get; set; }
        public bool EstObligatoire { get; set; }
        public string Commentaire { get; set; }
        public Nullable<int> IdMembrePrestation { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public Nullable<System.DateTime> DateModification { get; set; }
        public string ChargePar { get; set; }
        public string Statut { get; set; }
        public string Par { get; set; }
        public byte[] Fichier { get; set; }
        public string ContentType { get; set; }
    
        public virtual Demandes Demandes { get; set; }
        public virtual DocumentsRequis DocumentsRequis { get; set; }
        public virtual DocumentTypes DocumentTypes { get; set; }
        public virtual Membres_x_Prestations Membres_x_Prestations { get; set; }
    }
}
