//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbassyDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentsRequis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentsRequis()
        {
            this.Documents = new HashSet<Documents>();
        }
    
        public int Id { get; set; }
        public string Label { get; set; }
        public int IdDocumentType { get; set; }
        public int IdEntitePrestation { get; set; }
        public bool EstObligatoire { get; set; }
        public Nullable<int> indice { get; set; }
        public string Operateur { get; set; }
        public Nullable<int> indiceR { get; set; }
        public bool VersionPapierObligatoire { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documents> Documents { get; set; }
        public virtual Entites_x_Prestations Entites_x_Prestations { get; set; }
        public virtual DocumentTypes DocumentTypes { get; set; }
    }
}
