//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbassyDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entites_x_Tranches
    {
        public int IdService { get; set; }
        public int IdTranche { get; set; }
        public short Capacity { get; set; }
        public short Occupied { get; set; }
    
        public virtual Entites Entites { get; set; }
        public virtual Tranches Tranches { get; set; }
    }
}
