//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbassyDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entites
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entites()
        {
            this.HorairesCanvasServices = new HashSet<HorairesCanvasServices>();
            this.JoursFeriesPosteConsulaire = new HashSet<JoursFeriesPosteConsulaire>();
            this.JoursNationauxPosteConsulaire = new HashSet<JoursNationauxPosteConsulaire>();
            this.PlannigTravailPosteConsulaire = new HashSet<PlannigTravailPosteConsulaire>();
            this.Tranches = new HashSet<Tranches>();
            this.Entites1 = new HashSet<Entites>();
            this.Entites_x_Prestations = new HashSet<Entites_x_Prestations>();
            this.Entites_x_Tranches = new HashSet<Entites_x_Tranches>();
            this.Utilisateurs = new HashSet<Utilisateurs>();
            this.Pays1 = new HashSet<Pays>();
            this.Decoupages = new HashSet<Decoupages>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Label { get; set; }
        public Nullable<int> IdEntiteSuperieur { get; set; }
        public int TimeOffsetInHours { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Adresse { get; set; }
        public string Fax { get; set; }
        public Nullable<int> IdPays { get; set; }
        public Nullable<int> IdService { get; set; }
    
        public virtual Pays Pays { get; set; }
        public virtual Services Services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorairesCanvasServices> HorairesCanvasServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JoursFeriesPosteConsulaire> JoursFeriesPosteConsulaire { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JoursNationauxPosteConsulaire> JoursNationauxPosteConsulaire { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlannigTravailPosteConsulaire> PlannigTravailPosteConsulaire { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tranches> Tranches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entites> Entites1 { get; set; }
        public virtual Entites Entites2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entites_x_Prestations> Entites_x_Prestations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entites_x_Tranches> Entites_x_Tranches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Utilisateurs> Utilisateurs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pays> Pays1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Decoupages> Decoupages { get; set; }
    }
}
