//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbassyDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorairesCanvas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HorairesCanvas()
        {
            this.HorairesCanvasServices = new HashSet<HorairesCanvasServices>();
            this.PlannigTravailPosteConsulaire = new HashSet<PlannigTravailPosteConsulaire>();
            this.Tranches = new HashSet<Tranches>();
        }
    
        public int ID { get; set; }
        public string Label { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public int IDCalendrierCanvas { get; set; }
        public Nullable<short> Capacity { get; set; }
    
        public virtual CalendrierCanvas CalendrierCanvas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorairesCanvasServices> HorairesCanvasServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlannigTravailPosteConsulaire> PlannigTravailPosteConsulaire { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tranches> Tranches { get; set; }
    }
}
