//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbassyDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorairesCanvasServices
    {
        public int Id { get; set; }
        public int IdService { get; set; }
        public int IdHorairesCanvas { get; set; }
        public short Capacity { get; set; }
    
        public virtual Entites Entites { get; set; }
        public virtual HorairesCanvas HorairesCanvas { get; set; }
    }
}
