//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbassyDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Immatriculation
    {
        public int Id { get; set; }
        public string NummeroImmatriculation { get; set; }
        public string Nom { get; set; }
        public string NomArabe { get; set; }
        public string Prenom { get; set; }
        public string PrenomArabe { get; set; }
        public string PrenomPere { get; set; }
        public string PrenomPereArabe { get; set; }
        public string NomCompletMere { get; set; }
        public string NomCompletMereArabe { get; set; }
        public int Sexe { get; set; }
        public Nullable<int> SituationFamilial { get; set; }
        public Nullable<System.DateTime> DateNaissance { get; set; }
        public string VilleNaissance { get; set; }
        public string VilleNaissanceEpouse { get; set; }
        public Nullable<int> IdPaysNaissance { get; set; }
        public Nullable<int> IdPaysNaissanceEpouse { get; set; }
        public string LieuNaissance { get; set; }
        public string LieuNaissanceArabe { get; set; }
        public string NomCompletEpouse { get; set; }
        public Nullable<System.DateTime> DateNaissanceEpouse { get; set; }
        public string LieuNaissanceEpouse { get; set; }
        public string NumeroPasseport { get; set; }
        public Nullable<System.DateTime> DateDelivrancePasseport { get; set; }
        public string NumeroCine { get; set; }
        public Nullable<System.DateTime> DateDelivranceCine { get; set; }
        public Nullable<System.DateTime> DateEntree { get; set; }
        public Nullable<int> TypeSejour { get; set; }
        public Nullable<System.DateTime> DateValiditeCarteSejour { get; set; }
        public Nullable<int> TypeCarteSejour { get; set; }
        public string TypeCarteSejourAlt { get; set; }
        public string NumeroCarteSejour { get; set; }
        public string NumeroCarteCitoyennete { get; set; }
        public Nullable<System.DateTime> DateRemiseCarteCitoyennete { get; set; }
        public string AdresseActuelle { get; set; }
        public string AdresseActuelleArabe { get; set; }
        public string AdresseVille { get; set; }
        public string AdresseVilleArabe { get; set; }
        public Nullable<int> IdPaysResidence { get; set; }
        public string CodePostal { get; set; }
        public string EtatRegionArabe { get; set; }
        public string EtatRegion { get; set; }
        public string NumeroPortable { get; set; }
        public string NumeroFixe { get; set; }
        public string AdresseEmail { get; set; }
        public string AdresseMaroc { get; set; }
        public string NomContactMaroc { get; set; }
        public string TelephoneContactMaroc { get; set; }
        public string AdresseContactMaroc { get; set; }
        public string NomContactEtranger { get; set; }
        public string TelephoneContactEtranger { get; set; }
        public string AdresseContactEtranger { get; set; }
        public Nullable<int> NiveauEtudes { get; set; }
        public string ProfessionActuelle { get; set; }
        public string EtablissementEtudes { get; set; }
        public Nullable<int> EtudesPoursuivies { get; set; }
        public string DisciplineSpecialisation { get; set; }
        public string Employeur { get; set; }
        public byte[] Photo { get; set; }
        public string NationaliteEpouse { get; set; }
        public string CineEpouse { get; set; }
        public Nullable<System.DateTime> DateDelivranceCineEpouse { get; set; }
        public string TelephoneEpouse { get; set; }
        public Nullable<int> NombreEnfants { get; set; }
        public string LieuDelivrancePasseport { get; set; }
    
        public virtual Demandes Demandes { get; set; }
        public virtual Pays Pays { get; set; }
        public virtual Pays Pays1 { get; set; }
        public virtual Pays Pays2 { get; set; }
    }
}
