//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbassyDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class JoursNationaux
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JoursNationaux()
        {
            this.JoursNationauxPosteConsulaire = new HashSet<JoursNationauxPosteConsulaire>();
        }
    
        public int Id { get; set; }
        public string Label { get; set; }
        public int Jour { get; set; }
        public int Mois { get; set; }
        public string MoisL { get; set; }
        public int IdPays { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JoursNationauxPosteConsulaire> JoursNationauxPosteConsulaire { get; set; }
        public virtual Pays Pays { get; set; }
    }
}
