//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbassyDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class JoursFeriesPosteConsulaire
    {
        public int id { get; set; }
        public int IdEntite { get; set; }
        public int IdJoursFeries { get; set; }
    
        public virtual Entites Entites { get; set; }
        public virtual JoursFeries JoursFeries { get; set; }
    }
}
