//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbassyDal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBAcces : DbContext
    {
        public DBAcces()
            : base("name=DBAcces")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CalendrierCanvas> CalendrierCanvas { get; set; }
        public virtual DbSet<Decoupages> Decoupages { get; set; }
        public virtual DbSet<Demandes> Demandes { get; set; }
        public virtual DbSet<Documents> Documents { get; set; }
        public virtual DbSet<DocumentsRequis> DocumentsRequis { get; set; }
        public virtual DbSet<DocumentTypes> DocumentTypes { get; set; }
        public virtual DbSet<Entites> Entites { get; set; }
        public virtual DbSet<Entites_x_Prestations> Entites_x_Prestations { get; set; }
        public virtual DbSet<Entites_x_Tranches> Entites_x_Tranches { get; set; }
        public virtual DbSet<ExtensionsTypes> ExtensionsTypes { get; set; }
        public virtual DbSet<Groupes> Groupes { get; set; }
        public virtual DbSet<HorairesCanvas> HorairesCanvas { get; set; }
        public virtual DbSet<HorairesCanvasServices> HorairesCanvasServices { get; set; }
        public virtual DbSet<Immatriculation> Immatriculation { get; set; }
        public virtual DbSet<JoursFeries> JoursFeries { get; set; }
        public virtual DbSet<JoursFeriesPosteConsulaire> JoursFeriesPosteConsulaire { get; set; }
        public virtual DbSet<JoursNationaux> JoursNationaux { get; set; }
        public virtual DbSet<JoursNationauxPosteConsulaire> JoursNationauxPosteConsulaire { get; set; }
        public virtual DbSet<JoursWeekEnd> JoursWeekEnd { get; set; }
        public virtual DbSet<Langues> Langues { get; set; }
        public virtual DbSet<Membres> Membres { get; set; }
        public virtual DbSet<Membres_x_Prestations> Membres_x_Prestations { get; set; }
        public virtual DbSet<NatureRequete> NatureRequete { get; set; }
        public virtual DbSet<Pays> Pays { get; set; }
        public virtual DbSet<PlannigTravailPays> PlannigTravailPays { get; set; }
        public virtual DbSet<PlannigTravailPosteConsulaire> PlannigTravailPosteConsulaire { get; set; }
        public virtual DbSet<Prestations> Prestations { get; set; }
        public virtual DbSet<PrestationsDocumentTypes> PrestationsDocumentTypes { get; set; }
        public virtual DbSet<Professions> Professions { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<ServicesPrestations> ServicesPrestations { get; set; }
        public virtual DbSet<Theme> Theme { get; set; }
        public virtual DbSet<Traduction> Traduction { get; set; }
        public virtual DbSet<Tranches> Tranches { get; set; }
        public virtual DbSet<TypeDecoupage> TypeDecoupage { get; set; }
        public virtual DbSet<TypeJoursFeries> TypeJoursFeries { get; set; }
        public virtual DbSet<Utilisateurs> Utilisateurs { get; set; }
    }
}
