//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbassyDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlannigTravailPosteConsulaire
    {
        public int Id { get; set; }
        public int IdEntite { get; set; }
        public int IdPlannigTravailPays { get; set; }
        public int IdCalendrierCanvas { get; set; }
        public Nullable<int> IDHorairesCanvas { get; set; }
        public System.DateTime DateDebut { get; set; }
        public System.DateTime DateFin { get; set; }
        public Nullable<short> Capacity { get; set; }
    
        public virtual CalendrierCanvas CalendrierCanvas { get; set; }
        public virtual Entites Entites { get; set; }
        public virtual HorairesCanvas HorairesCanvas { get; set; }
        public virtual PlannigTravailPays PlannigTravailPays { get; set; }
    }
}
