//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbassyDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrestationsDocumentTypes
    {
        public int Id { get; set; }
        public int IdDocumentType { get; set; }
        public int IdPrestation { get; set; }
        public bool EstObligatoire { get; set; }
        public Nullable<int> indice { get; set; }
        public string Operateur { get; set; }
        public Nullable<int> indiceR { get; set; }
        public bool VersionPapierObligatoire { get; set; }
    
        public virtual DocumentTypes DocumentTypes { get; set; }
        public virtual Prestations Prestations { get; set; }
    }
}
