//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbassyDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traduction
    {
        public int Id { get; set; }
        public string Table { get; set; }
        public int IdLigne { get; set; }
        public string Colonne { get; set; }
        public string Traduction1 { get; set; }
        public Nullable<int> IdLangue { get; set; }
    
        public virtual Langues Langues { get; set; }
    }
}
