//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbassyDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tranches
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tranches()
        {
            this.Demandes = new HashSet<Demandes>();
            this.Entites_x_Tranches = new HashSet<Entites_x_Tranches>();
        }
    
        public int Id { get; set; }
        public System.DateTime FromTime { get; set; }
        public System.DateTime ToTime { get; set; }
        public int IDCalendrierCanvas { get; set; }
        public int IDHorairesCanvas { get; set; }
        public int codePosteConsulaire { get; set; }
        public int IdPlannigTravailPays { get; set; }
        public string TypeJour { get; set; }
    
        public virtual CalendrierCanvas CalendrierCanvas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Demandes> Demandes { get; set; }
        public virtual Entites Entites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entites_x_Tranches> Entites_x_Tranches { get; set; }
        public virtual HorairesCanvas HorairesCanvas { get; set; }
        public virtual PlannigTravailPays PlannigTravailPays { get; set; }
    }
}
