//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbassyDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateurs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utilisateurs()
        {
            this.Demandes = new HashSet<Demandes>();
            this.Groupes = new HashSet<Groupes>();
            this.Roles = new HashSet<Roles>();
        }
    
        public int Id { get; set; }
        public string Label { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public Nullable<int> IdEntite { get; set; }
        public System.DateTime DateNaissance { get; set; }
        public string CNIE { get; set; }
        public string Email { get; set; }
        public string Login { get; set; }
        public string PW { get; set; }
        public Nullable<System.DateTime> PW_Date { get; set; }
        public string NumeroImm { get; set; }
        public string IdInstance { get; set; }
        public string Telephone { get; set; }
        public string Adresse { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> IdPays { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Demandes> Demandes { get; set; }
        public virtual Entites Entites { get; set; }
        public virtual Pays Pays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Groupes> Groupes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Roles> Roles { get; set; }
    }
}
