'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Accessoire_Visuel
    Public Property IdAccessoire_Visuel As Integer
    Public Property MimeType As String
    Public Property ImageAccessoire As Byte()
    Public Property Sku As String
    Public Property DateAjout As Nullable(Of Date)
    Public Property Taille As Nullable(Of Integer)
    Public Property IdAccessoire As Nullable(Of Integer)

    Public Overridable Property Accessoires As Accessoire

End Class
