'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Accessoire
    Public Property IdAccessoire As Integer
    Public Property IdCategorie As String
    Public Property Sku As String
    Public Property Stock As Nullable(Of Integer)
    Public Property PriceDeBase As Nullable(Of Double)
    Public Property PrixDeVente As Nullable(Of Double)
    Public Property PrixPublic As Nullable(Of Double)
    Public Property Libelle_Francais As String
    Public Property Libelle_Anglais As String
    Public Property Description As String
    Public Property Description_Html As String
    Public Property Support As String
    Public Property SupportTechnique As String
    Public Property IdStatut As String
    Public Property Ean As String
    Public Property UrlImage As String
    Public Property DateAjout As Nullable(Of Date)
    Public Property DureeDeGarantie As Nullable(Of Integer)
    Public Property Toremain As String
    Public Property NombreDeCompatible As Nullable(Of Integer)
    Public Property ImageAccessoire As Byte()

    Public Overridable Property Accessoires_Proprietes As ICollection(Of Accessoire_Propriete) = New HashSet(Of Accessoire_Propriete)
    Public Overridable Property Compatibilites As ICollection(Of Compatibilite) = New HashSet(Of Compatibilite)
    Public Overridable Property Accessoires_Visuels As ICollection(Of Accessoire_Visuel) = New HashSet(Of Accessoire_Visuel)
    Public Overridable Property Categories As Categorie
    Public Overridable Property Statuts As Statut

End Class
