'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Accessoire_Propriete
    Public Property IdAccessoire_Propriete As Integer
    Public Property Sku As String
    Public Property Cle As String
    Public Property Valeur As String
    Public Property Parent As Nullable(Of Integer)
    Public Property IdAccessoire As Integer

    Public Overridable Property Accessoires As Accessoire

End Class
