'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Compatiblite
    Public Property IdCompatiblite As Integer
    Public Property IdModele As Integer
    Public Property IdAccessoire As Integer
    Public Property DateDeMiseAjour As Date

    Public Overridable Property Modele As Modele
    Public Overridable Property Accessoire As Accessoire

End Class
