'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class dbgestelacEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=dbgestelacEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Accessoires() As DbSet(Of Accessoire)
    Public Overridable Property Accessoires_Proprietes() As DbSet(Of Accessoire_Propriete)
    Public Overridable Property Accessoires_Visuels() As DbSet(Of Accessoire_Visuel)
    Public Overridable Property Categories() As DbSet(Of Categorie)
    Public Overridable Property Compatibilites() As DbSet(Of Compatibilite)
    Public Overridable Property Marques() As DbSet(Of Marque)
    Public Overridable Property Modeles() As DbSet(Of Modele)
    Public Overridable Property Modeles_Proprietes() As DbSet(Of Modele_Propriete)
    Public Overridable Property Statuts() As DbSet(Of Statut)

End Class
