'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Marque
    Public Property IdMarque As Integer
    Public Property NomDeLaMarque As String
    Public Property IdGsmArena As Integer

    Public Overridable Property Modeles As ICollection(Of Modele) = New HashSet(Of Modele)

End Class
