'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Modele
    Public Property IdModele As Integer
    Public Property NomDuModele As String
    Public Property ReferenceTechnique As String
    Public Property UrlImage As String
    Public Property GsmArenaUrl As String
    Public Property IdMarque As Integer
    Public Property NomDeLaMarque As String

    Public Overridable Property Compatibilites As ICollection(Of Compatibilite) = New HashSet(Of Compatibilite)
    Public Overridable Property Marques As Marque
    Public Overridable Property Modeles_Proprietes As ICollection(Of Modele_Propriete) = New HashSet(Of Modele_Propriete)

End Class
