'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Modele_Propriete
    Public Property IdModele_Propriete As Integer
    Public Property Cle As String
    Public Property Valeur As String
    Public Property IdModele As Integer
    Public Property NomDuModele As String
    Public Property NomDeLaMarque As String

    Public Overridable Property Modeles As Modele

End Class
