'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Statut
    Public Property IdStatut As String
    Public Property Valeur As Nullable(Of Integer)

    Public Overridable Property Accessoires As ICollection(Of Accessoire) = New HashSet(Of Accessoire)

End Class
