//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NigthlyService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MMOBJS
    {
        public int EMPID { get; set; }
        public int OBJECT { get; set; }
        public int TYPE { get; set; }
        public byte[] LNL_BLOB { get; set; }
        public Nullable<System.DateTime> LASTCHANGED { get; set; }
        public Nullable<int> ACCEPTANCETHRESHOLD { get; set; }
        public Nullable<short> BIO_BODYPART { get; set; }
        public byte[] LNL_BLOB_TXT { get; set; }
        public string FORMAT_IMAGE { get; set; }
    }
}
