//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NightlyServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONNEL
    {
        public int EMPID { get; set; }
        public string FULLNAME { get; set; }
        public byte[] LNL_BLOB { get; set; }
        public string CARD_NUMBER { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> ACTIVATION { get; set; }
        public Nullable<System.DateTime> DEACTIVATION { get; set; }
    }
}
