//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliotheque
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chantiers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chantiers()
        {
            this.Statut = true;
        }
    
        public int IdChantier { get; set; }
        public string LibelleChantier { get; set; }
        public System.DateTime DateDebut { get; set; }
        public System.DateTime DateFin { get; set; }
        public bool Statut { get; set; }
        public int ProjetsIdProjet { get; set; }
    
        public virtual Projets Projets { get; set; }
    }
}
